name: recursive_aggregates  

dependencies:
  - python=3.10
  - clingo=5.7.0
  - boost-cpp
  - pip
  - pip:
      - argparse==1.4.0
      - lxml
      - psutil
      - numpy
      - apgl
      - networkx
      - pandas
